spring:
  application:
    name: prod-ready-features
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ProdReadyFeatures}
    username: ${DB_USER:diwakar}
    password: ${DB_PW:diwakar}

#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
#    defer-datasource-initialization: true

logging:
  level:
    com: TRACE
  pattern:
    console: "%d [%level] %c{1.} [%t] %m%n"
  file:
    name: application.log

server:
  port: 8000

Employee:
  ServiceUrl: "http://localhost:8001"